from turtle import *
screen=getscreen()
screen.setup(900,900)
speed(200)
screen=Screen()
pensize(5)
bgcolor("#d9d2e9")
bgpic("unknown.png")
up()
goto(300, 200)
down()
style=("Comic Sans", 20)
write("FEDDY", font=style, align="center")
up()
goto(250, -330)
down()
style1=("comic sans", 14)
write("Do you like our peepee?", font=style1, align="center")

up()
goto(-200, 200)
down()

def half_circle(x):
    for i in range(x):
        right(1)
        forward(2)

def body():
    color("Red")
    begin_fill()
    left(90)
    pencolor("black")

    half_circle(165)
    right(10)
    forward(220)
    left(90)
    half_circle(205)

    up()
    goto(-3,-13)
    down()
    left(180)
    half_circle(280)
    left(43)
    forward(266)
    end_fill()

def leg1(x, y, z):
    up()
    goto(x, y)
    down()
    color("red")
    pencolor("black")
    begin_fill()
    left(z)
    forward(100)
    def small():
        for i in range(45):
            right(2)
            forward(1)
    small()
    forward(20)
    small()
    forward(98)
    end_fill()

def glass():
    color("#59b5ff")
    pencolor("black")
    begin_fill()
    up()
    goto(-100, 220)
    down()
    right(280)
    circle(60, -180)
    right(180)
    forward(100)
    circle(-60, 180)
    forward(100)
    end_fill()

def light_glass():
    up()
    goto(-170, 160)
    down()
    color("#a2d4fc")
    begin_fill()
    circle(20, -180)
    right(180)
    forward(50)
    circle(-20, 180)
    forward(50)
    end_fill()

def light():
    up()
    goto(100, -25)
    down()
    right(30)
    pencolor("#f4cccc")
    pensize(10)
    circle(100, -30)
    up()
    goto(0, -40)
    down()
    left(35)
    circle(100, -30)

body()
leg1(98,-200, 180)
leg1(-25, -220, 155)
glass()
light_glass()
light()
mainloop()